### ISSUE TITLE
Invalid security or form key. Please refresh the page.

### ISSUE THREAD

**Issue by vandark25** [hungersoft/magento2-image-clean#6]
On 2.3.7 always show the error on backend
Invalid security or form key. Please refresh the page.

**Comment by hgati** [comment]
I recommend this module.

https://github.com/baldwin-agency/magento2-module-image-cleanup

**Comment by hgati** [comment]
> https://github.com/baldwin-agency/magento2-module-image-cleanup

I recommend this module.
https://github.com/baldwin-agency/magento2-module-image-cleanup

**Comment by vandark25** [comment]
Solved by
